# Not exactly the same as SRResNet in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>
# With 16 Residual blocks w/o BN

#### general settings
name: debug_001_SRResNetx4_DIV2K  # please remove 'debug_' during training
use_tb_logger: true
model: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LRHR
    dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub.lmdb
    dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub_bicLRx4.lmdb
    subset_file: ~

    use_shuffle: true
    n_workers: 8
    batch_size: 16
    HR_size: 128 # 128 | 192
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_set5
    mode: LRHR
    dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/val_set5/Set5
    dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/val_set5/Set5_bicLRx4

#### network structures
network_G:
  which_model_G: sr_resnet
  norm_type: ~
  mode: CNA
  nf: 64
  nb: 16
  in_nc: 3
  out_nc: 3

#### path
path:
  pretrain_model_G: ~
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  lr_steps: [200000, 400000, 600000, 800000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
