#### general settings
name: debug_002_RRDB_ESRGAN_x4_DIV2K  # please remove 'debug_' during training
use_tb_logger: true
model: srragan
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LRHR
    dataroot_GT: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub.lmdb
    dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub_bicLRx4.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 16
    GT_size: 128 # 128 | 192
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_set14_part
    mode: LRHR
    dataroot_GT: /mnt/SSD/xtwang/BasicSR_datasets/val_set14_part/Set14
    dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/val_set14_part/Set14_bicLRx4

#### network structures
network_G:
  which_model_G: RRDB_net
  norm_type: ~
  mode: CNA
  nf: 64
  nb: 23
  in_nc: 3
  out_nc: 3
  gc: 32
  group: 1
network_D:
  which_model_D: discriminator_vgg_128
  norm_type: batch
  act_type: leakyrelu
  mode: CNA
  nf: 64
  in_nc: 3

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/RRDB_PSNR_x4.pth
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 500000
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: vanilla
  gan_weight: !!float 5e-3

  # for wgan-gp
  # D_update_ratio: 1
  # D_init_iters: 0
  # gp_weigth: 10

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
